### ISSUE TITLE
Start/Stop signal for Mimosa26 configuration

### ISSUE THREAD

**Issue by YannickDieter** [SiLab-Bonn/pymosa#1]
Sometimes it happens that M26 cannot be configured. This is caused due to unstable state of start/stop signal. 

The solution for this problem is to use the additional ETH connection for this signal.

**Comment by idcs0906** [comment]
It is possible now to send the signals to the CLK board in the telescope through the first (0) Ethernet port of the MMC3 board. Start, Reset, Speak and Clock functions were set to proper initial values in software.
