### ISSUE TITLE
Hit correlator shows row-colleration as column corrleation  and column as row.

### ISSUE THREAD

**Issue by thirono** [SiLab-Bonn/pymosa#18]
Row-correlation is shown as column-correlation. (valid data for present column-correlation is only from 0 to 576, even n_column in the yaml file set to 1152).

**Comment by leloup314** [comment]
Is this still the correlator I wrote?

**Comment by YannickDieter** [comment]
No this is a new one. This issue will be fixed with #19.

**Comment by laborleben** [comment]
@YannickDieter @thirono Is this related to the online monitor?

**Comment by YannickDieter** [comment]
It was related to our pymosa online monitor. As already mentioned this is fixed with #19

**Comment by laborleben** [comment]
So then I close this.
